configfile: "config/config.yaml"

include: "rules/common.smk"

def find_files(wc):
    f = checkpoints.run_simpy.get().output[0]
    file_name = []
    with open("file_names.txt", "r") as file:
        file_name = file.read().splitlines()
    return expand("simulated_reads/{swapped_genome}_sim{rn}.fastq", swapped_genome = file_name, rn=["R1","R2"]) 


ruleorder:
    run_simpy > sim_Genomes 
rule all:
    input: 
        find_files

checkpoint run_simpy:
    output:
        "file_names.txt"
    conda:
        "envs/env.yaml"
    script:
        "sim.py"

rule sim_Genomes:
    input:
        "mixed_blocks/{swapped_genome}.fa"
    output:
        read_1 = "simulated_reads/{swapped_genome}_simR1.fastq",
        read_2 = "simulated_reads/{swapped_genome}_simR2.fastq",
    conda:
        "envs/env.yaml"
    shell:
        # wgsim -1 INT len 1st read -2 INT len 1st read -r FLOAT rate of mutations -R FLOAT fraction of indels 
        # -X FLOAT probability an indel is extended -e FLOAT base error rate 
        # i.e wgsim -1 150 -2 150 -r 0 -R 0 -X 0 -e 0 reference_input.fasta ref_output_1.fastq ref_output_2.fastq
        """
        wgsim -1 150 -2 150 -r 0 -R 0.0001 -X 0 -e 0 {input} {output.read_1} {output.read_2}
        """


